return_codes:
    ok:                                   0
    exceptions:
        ws_sfr:                           6000
        access_denied:
            access_denied:                3000

        invalid_arguments:
            invalid_arguments:            4000

        not_found:
            not_found_exception:          2000
            msisdn:                       2001
            client:                       2002
            article:                      2003
            num_abo:                      2004
            client_active:                2005
            imsi:                         2006
            nsce:                         2007

        technical:
            technical:                    1000
            numabo_msisdn:                1001

        eligibility:
            client_not_eligible:          5000
            client_not_eligible:          5000
            client_not_authorized:        5100
            client_not_full_mvno:         5200
            femto_already_active:         5300
            femto_option_active:          5400
            client_status_inactive:       5500
            client_liable:                5600
            client_terminated:            5700