Omea\GestionTelco\PatesBundle\Types\EligibilityRequest:
    properties:
        msisdn:
            - NotBlank: ~
            - NotNull: ~
            - Omea\GestionTelco\PatesBundle\Validator\Constraint\IsValidMSISDN: ~
Omea\GestionTelco\PatesBundle\Types\CreateOrderRequest:
    properties:
        msisdn:
            - NotBlank: ~
            - NotNull: ~
            - Omea\GestionTelco\PatesBundle\Validator\Constraint\IsValidMSISDN: ~
Omea\GestionTelco\PatesBundle\Types\CancellationRequest:
    properties:
        msisdn:
            - NotBlank: ~
            - NotNull: ~
            - Omea\GestionTelco\PatesBundle\Validator\Constraint\IsValidMSISDN: ~
Omea\GestionTelco\PatesBundle\Types\ActivateFAPRequest:
    properties:
        msisdn:
            - NotBlank: ~
            - NotNull: ~
            - Omea\GestionTelco\PatesBundle\Validator\Constraint\IsValidMSISDN: ~
        imei:
            - NotBlank: ~
            - NotNull: ~
            - Omea\GestionTelco\PatesBundle\Validator\Constraint\IsValidIMEI: ~
Omea\GestionTelco\PatesBundle\Types\GetAdditionalsListRequest:
    properties:
        msisdn:
            - NotBlank: ~
            - NotNull: ~
            - Omea\GestionTelco\PatesBundle\Validator\Constraint\IsValidMSISDN: ~
Omea\GestionTelco\PatesBundle\Types\SetAdditionalsListRequest:
    properties:
        msisdn:
            - NotBlank: ~
            - NotNull: ~
            - Omea\GestionTelco\PatesBundle\Validator\Constraint\IsValidMSISDN: ~
        userList:
            - Count:
                min: 0
                max: 9
            - All:
                - Omea\GestionTelco\PatesBundle\Validator\Constraint\IsValidMSISDN: ~
Omea\GestionTelco\PatesBundle\Types\ChangeMsisdnRequest:
    properties:
        oldMsisdn:
            - NotBlank: ~
            - NotNull: ~
            - Omea\GestionTelco\PatesBundle\Validator\Constraint\IsValidMSISDN: ~
        newMsisdn:
            - NotBlank: ~
            - NotNull: ~
            - Omea\GestionTelco\PatesBundle\Validator\Constraint\IsValidMSISDN: ~
Omea\GestionTelco\PatesBundle\Types\ChangeImsiRequest:
    properties:
        msisdn:
            - NotBlank: ~
            - NotNull: ~
            - Omea\GestionTelco\PatesBundle\Validator\Constraint\IsValidMSISDN: ~
        newImsi:
            - NotBlank: ~
            - NotNull: ~
            - Omea\GestionTelco\PatesBundle\Validator\Constraint\IsValidIMSI: ~