imports:
    - { resource: doctrine.yml }

services:
    omea_gestion_telco_evenements.services.evenements:
        class: Omea\GestionTelco\EvenementsBundle\Services\EvenementsService
        arguments:
            - @validator
            - @logger
            - @omea_gestion_telco_evenements.services.saveevenement
            - @omea_gestion_telco_evenements.evenementmanager
            - @omea_gestion_telco_evenements.evenement.repository

    omea_gestion_telco_evenements.services.saveevenement:
        class: Omea\GestionTelco\EvenementsBundle\Services\SaveEvenementService
        arguments:
            - @logger
            - @doctrine

    # orchestrateur des événements
    omea_gestion_telco_evenements.evenementmanager:
        class: Omea\GestionTelco\EvenementsBundle\EvenementManager\EvenementManager

    # gestionnaires d'événements prenant en charge des codes événements
    omea_gestion_telco_evenements.evenementmanager.handler.fairuse:
        class: Omea\GestionTelco\EvenementsBundle\EvenementManager\Handler\FairUseHandler
        tags:
            - { name: omea_gestion_telco_evenements.evenementmanager.handler }
    
    omea_gestion_telco_evenements.evenementmanager.handler.antifraude:
        class: Omea\GestionTelco\EvenementsBundle\EvenementManager\Handler\AntiFraudeHandler
        tags:
            - { name: omea_gestion_telco_evenements.evenementmanager.handler }

    omea_gestion_telco_evenements.evenementmanager.handler.changecountry:
        class: Omea\GestionTelco\EvenementsBundle\EvenementManager\Handler\ChangeCountryHandler
        tags:
            - { name: omea_gestion_telco_evenements.evenementmanager.handler }