<?php

namespace Omea\Entity\GestionEvenements;

/**
 * GestionEvenementErreurRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GestionEvenementErreurRepository extends \Doctrine\ORM\EntityRepository
{
    
}
