services:
    omea_gestion_telco_evenement.evenement.repository:
        factory_service: 'doctrine.orm.gestionEvenements_entity_manager'
        factory_method: 'getRepository'
        class: 'Omea\Entity\GestionEvenements\EvenementRepository'
        arguments: ['Omea\Entity\GestionEvenements\Evenement']
    
    omea_gestion_telco_evenement.evenementdefinition.repository:
        factory_service: 'doctrine.orm.gestionEvenements_entity_manager'
        factory_method: 'getRepository'
        class: 'Omea\Entity\GestionEvenements\EvenementDefinitionRepository'
        arguments: ['Omea\Entity\GestionEvenements\EvenementDefinition']
      
    omea_gestion_telco_evenement.stockmsisdn.repository:
        factory_service: 'doctrine.orm.main_entity_manager'
        factory_method: 'getRepository'
        class: 'Omea\Entity\Main\StockMsisdnRepository'
        arguments: ['Omea\Entity\Main\StockMsisdn']